[project]
name = "document-composer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dcp-engine",
    "dcp-api",
    "dcp-shared",
    "pydantic>=2.13.4",
]

[dependency-groups]
dev = ["pytest>=9.1.1"]

[tool.uv.workspace]
members = [
    "packages/engine",
    "packages/api",
    "packages/shared",
]

[tool.uv.sources]
dcp-engine = { workspace = true }
dcp-shared = { workspace = true }
dcp-api = { workspace = true }
